// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneBooker.Modules.Users.Infrastructure.Persistance;

#nullable disable

namespace OneBooker.Modules.Users.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260610185855_Users_AddCustomer")]
    partial class Users_AddCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Users")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.Addresses.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "تبریز",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "ارومیه",
                            ProvinceId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "اردبیل",
                            ProvinceId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "اصفهان",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "کرج",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "ایلام",
                            ProvinceId = 6
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "بوشهر",
                            ProvinceId = 7
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "تهران",
                            ProvinceId = 8
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "شهرکرد",
                            ProvinceId = 9
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "بیرجند",
                            ProvinceId = 10
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "مشهد",
                            ProvinceId = 11
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "بجنورد",
                            ProvinceId = 12
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "اهواز",
                            ProvinceId = 13
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "زنجان",
                            ProvinceId = 14
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "سمنان",
                            ProvinceId = 15
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "زاهدان",
                            ProvinceId = 16
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "شیراز",
                            ProvinceId = 17
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "قزوین",
                            ProvinceId = 18
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "قم",
                            ProvinceId = 19
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "سنندج",
                            ProvinceId = 20
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "کرمان",
                            ProvinceId = 21
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "کرمانشاه",
                            ProvinceId = 22
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "یاسوج",
                            ProvinceId = 23
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "گرگان",
                            ProvinceId = 24
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "رشت",
                            ProvinceId = 25
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "خرم‌آباد",
                            ProvinceId = 26
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "ساری",
                            ProvinceId = 27
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "اراک",
                            ProvinceId = 28
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "بندرعباس",
                            ProvinceId = 29
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "همدان",
                            ProvinceId = 30
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "یزد",
                            ProvinceId = 31
                        });
                });

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.Addresses.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "ایران"
                        });
                });

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.Addresses.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Provinces", "Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            IsActive = true,
                            Name = "آذربایجان شرقی"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            IsActive = true,
                            Name = "آذربایجان غربی"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            IsActive = true,
                            Name = "اردبیل"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            IsActive = true,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            IsActive = true,
                            Name = "البرز"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            IsActive = true,
                            Name = "ایلام"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            IsActive = true,
                            Name = "بوشهر"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            IsActive = true,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            IsActive = true,
                            Name = "چهارمحال و بختیاری"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 1,
                            IsActive = true,
                            Name = "خراسان جنوبی"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 1,
                            IsActive = true,
                            Name = "خراسان رضوی"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 1,
                            IsActive = true,
                            Name = "خراسان شمالی"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 1,
                            IsActive = true,
                            Name = "خوزستان"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 1,
                            IsActive = true,
                            Name = "زنجان"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 1,
                            IsActive = true,
                            Name = "سمنان"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 1,
                            IsActive = true,
                            Name = "سیستان و بلوچستان"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 1,
                            IsActive = true,
                            Name = "فارس"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 1,
                            IsActive = true,
                            Name = "قزوین"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 1,
                            IsActive = true,
                            Name = "قم"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 1,
                            IsActive = true,
                            Name = "کردستان"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 1,
                            IsActive = true,
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 1,
                            IsActive = true,
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 23,
                            CountryId = 1,
                            IsActive = true,
                            Name = "کهگیلویه و بویراحمد"
                        },
                        new
                        {
                            Id = 24,
                            CountryId = 1,
                            IsActive = true,
                            Name = "گلستان"
                        },
                        new
                        {
                            Id = 25,
                            CountryId = 1,
                            IsActive = true,
                            Name = "گیلان"
                        },
                        new
                        {
                            Id = 26,
                            CountryId = 1,
                            IsActive = true,
                            Name = "لرستان"
                        },
                        new
                        {
                            Id = 27,
                            CountryId = 1,
                            IsActive = true,
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 28,
                            CountryId = 1,
                            IsActive = true,
                            Name = "مرکزی"
                        },
                        new
                        {
                            Id = 29,
                            CountryId = 1,
                            IsActive = true,
                            Name = "هرمزگان"
                        },
                        new
                        {
                            Id = 30,
                            CountryId = 1,
                            IsActive = true,
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 31,
                            CountryId = 1,
                            IsActive = true,
                            Name = "یزد"
                        });
                });

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.UserManagement.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers", "Users");
                });

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.UserManagement.Entities.ResetPasswordToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashedToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tokens", "Users");
                });

            modelBuilder.Entity("OneBooker.Modules.Users.Domain.UserManagement.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Users");
                });
#pragma warning restore 612, 618
        }
    }
}
